[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dasprocessor"
version = "0.0.1"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["libs"]
